version: '3'
services:
   db:
      image: 'mysql:5.7'
      command: --innodb-use-native-aio=0
      container_name: db
      restart: always
      tty: true
#      volumes:
#         - './mysql:/var/lib/mysql'
      environment:
         - MYSQL_DATABASE=Nginx_Node_db
         - MYSQL_ROOT_PASSWORD=root
      networks:
         - full-network

   app-node:
      build:
         context: ./node
      container_name: nodejs
      image: fabiopontess/app-node
      entrypoint: dockerize -wait tcp://db:3306 -timeout 90s docker-entrypoint.sh
      command: node index.js
      hostname: fabiopontes 
      ports:
         - "3000:3000"
      networks: 
         - full-network
      #volumes:
      #  - ./node:/usr/src/app
      tty: true
      depends_on:
         - db  



   nginx:
      build:
         context: ./nginx
      image: fabiopontess/nginxf
      container_name: nginx
      hostname: nginx
      tty: true
      ports:
         - '8080:80'
      depends_on:
         - app-node
      networks:
         - full-network

networks:
  full-network:
    driver: bridge
